version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y dbus systemd gnome-keyring

      - run:
          name: Start systemd-logind Service
          command: |
            sudo systemctl enable systemd-logind
            sudo systemctl start systemd-logind
            sleep 5

      - run:
          name: Verify systemd-logind is Active
          command: |
            while ! systemctl is-active --quiet systemd-logind; do
              echo "Waiting for systemd-logind to become active..."
              sleep 2
            done
            echo "systemd-logind is active."

      - run:
          name: Verify D-Bus Services
          command: |
            systemctl status systemd-logind
            systemctl status org.freedesktop.hostname1
            systemctl status org.freedesktop.Accounts
            systemctl status gnome-keyring
